MODE="aggressive"
CHECK_INTERVAL=600

BAD_PATHS=(
    "$HOME/.local/share/Steam/steamapps/common/dota 2 beta"
    "$HOME/.local/share/Steam/steamapps/appmanifest_570.acf"
)

BAD_PROCESSES=(
    "steam"
    "dota2"
)