MODE="dry-run"
CHECK_INTERVAL=600

BAD_PATHS=(
    "~/.local/share/Steam/steamapps/common/dota 2 beta"
    "~/.local/share/Steam/steamapps/appmanifest_570.acf"
)

BAD_PROCESSES=(
    "steam"
    "dota2"
)